import { DataStore } from '../../src/datastore';

const resolvedFn = <T>(value?: T) => jest.fn().mockResolvedValue(value);

export const createDataStoreMock = (): jest.Mocked<DataStore> => ({
  getChurch: resolvedFn(),
  getDashboardSnapshot: resolvedFn(),
  listUsers: resolvedFn(),
  getUserById: resolvedFn(),
  getUserByEmail: resolvedFn(),
  getUserProfile: resolvedFn(),
  createUser: resolvedFn(),
  updateUser: resolvedFn(),
  deleteUser: resolvedFn(),
  listHouseholds: resolvedFn([]),
  getHouseholdById: resolvedFn(),
  listGroups: resolvedFn(),
  getGroupById: resolvedFn(),
  getGroupMembers: resolvedFn(),
  addGroupMember: resolvedFn(),
  updateGroupMember: resolvedFn(),
  removeGroupMember: resolvedFn(),
  listEvents: resolvedFn(),
  getEventById: resolvedFn(),
  createEvent: resolvedFn(),
  updateEvent: resolvedFn(),
  deleteEvent: resolvedFn(),
  recordAttendance: resolvedFn(),
  listAnnouncements: resolvedFn(),
  markAnnouncementRead: resolvedFn(),
  createAnnouncement: resolvedFn(),
  updateAnnouncement: resolvedFn(),
  listFunds: resolvedFn(),
  listContributions: resolvedFn(),
  recordContribution: resolvedFn(),
  updateContribution: resolvedFn(),
  getGivingSummary: resolvedFn(),
  exportContributionsCsv: resolvedFn(),
  listRoles: resolvedFn([]),
  createRole: resolvedFn(),
  updateRole: resolvedFn(),
  deleteRole: resolvedFn(),
  createSession: resolvedFn(),
  getSessionByToken: resolvedFn(),
  upsertUserFromOAuth: resolvedFn(),
  listAuditLogs: resolvedFn(),
  createAuditLog: resolvedFn(),
});
